### ISSUE TITLE
Why is the test directory 'test' not 'tests'.

### ISSUE THREAD

**Issue by afrid18** [rpm-software-management/rpmlint#1032]
It is recommended by the python community that using `tests` as the testing directory instead of `test` for the python testing that uses pytest. Other programming communities use `test` as their testing directory that uses bash etc.

- rename `test` directory to `tests`

**Comment by afrid18** [comment]
After an approval, I will submit a pull request.

**Comment by Conan-Kudo** [comment]
Our tests predate our usage of pytest. They were a mixture of shell and Python. They've been totally reworked to fit through pytest, but we didn't bother to rename the directory because that makes GitHub's representation of the git history annoying.

Is there a particular guidance that says we _should_ use `tests` over `test`?

**Comment by afrid18** [comment]
> Is there a particular guidance that says we should use tests over test?

I guess no.

I am closing this now as didn't find a solid reference. Thank you.
