### ISSUE TITLE
is this version rpmlint can check bash command inside a spec file?

### ISSUE THREAD

**Issue by hzhang7** [rpm-software-management/rpmlint#1271]
rpmlint: rpmlint version 1.10 Copyright (C) 1999-2007 Frederic Lepied, Mandriva

my spec file include some bash command inside a spec file
%install
if [ `grep -c "test" /etc/os-release` == '1' ];then
   delete_files /etc/redis
if [ `grep -c "test" /etc/os-release` == '1' ];then
fi

rpmlint redis-server-aarch64.spec, it print out 0 errors, 0 warning

is there a way to detect this kind of error when using rpmlint?
![image](https://github.com/user-attachments/assets/41b4dfb0-f4ed-4114-b8ce-3db83bfec35d)

**Comment by danigm** [comment]
There's something like this done to check post scripts, but I don't think that this check is possible for every section, because of macros.

Maybe it's possible to do this just for `src` packages because there the spec file should be expanded, so we can try to check the content of `%install` section with `sh -n`.
