### ISSUE TITLE
RFE: Warn if HTTPS is available but not used

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpmlint#201]
Could we add a warning if http:// URL (or source or patch) is used, but https:// would work?

I might even work on this, but only if there is a consensus that it would be accepted.

I'd add it into https://github.com/rpm-software-management/rpmlint/blob/569c35a74f4461b44209f329992dca68e0fc4680/rpmlint/checks/AbstractCheck.py#L60

The warning could be `non-https-url`

**Comment by scarabeusiv** [comment]
The question is usefulness of this check as a whole honestly. Because we try to have the rpmlint self-contained I was actually planning to extract this online check away to separate or even delete it.

In general I just looped all the stuff we have in openSUSE Tumbleweed that points to http if it could point to https and <300 packages errored out. That means out of 130000 packages we could just tell people to use https every time?

**Comment by hroncok** [comment]
I'd like to tell people to use HTTPS. If this doesn't get accepted to rpmlint, I'll try fedora-review instead. And if it's not accepted there either, I can live with that.

**Comment by hroncok** [comment]
I don't want to warn people to use https if https is not available on that URL.
That is essentially a non-actionable warning.
We can fallback to that if offline.

**Comment by scarabeusiv** [comment]
Okay, in that case I agree with what you want to do. If you feel like it you can also split it to separate check that can be loaded as needed instead of being part of the base class :)

**Comment by hroncok** [comment]
> If you feel like it you can also split it to separate check that can be loaded as needed instead of being part of the base class :)

I'm afraid I wouldn't know how to do this. I'll try to extend the existing check and see where would that lead me.
