### ISSUE TITLE
Merge in tests/testsuite from openSUSE rpmlint-tests

### ISSUE THREAD

**Issue by scarabeusiv** [rpm-software-management/rpmlint#227]
There is shell testsuite residing at https://github.com/openSUSE/rpmlint-tests. This should not be needed and we should have all the coverage inplace in the rpmlint tests here.

This is tied to https://github.com/openSUSE/rpmlint-checks which contain some extra checks and need to be merged too (the enablement later on is simply tied to the distribution configuration, yet the checks can all be at one place with no problem).

The merge needs to happen prior 2.0 release that changed the syntax so none of the openSUSE checks will work otherwise.

@dirkmueller what would be your suggestion how to tackle this; it will need to happen after we finish with pkg.py changes but then all the tests should be tweakable independently and the api on how they should work should not change anymore.

**Comment by Conan-Kudo** [comment]
None of the SUSE-specific checks should be pulled in. That means the SUSE FHS restrictions, BSD RC link enforcement, kmod packaging rules, etc. should not be incorporated upstream unless they are rationalized with the other major RPM distros (Fedora and Mageia).

**Comment by scarabeusiv** [comment]
@Conan-Kudo I am not saying to enable them by default just to have them in one repo, even now not all of the checks here are enabled by default.

**Comment by Conan-Kudo** [comment]
I don't want all the checks from openSUSE merged wholesale, even disabled.

**Comment by scarabeusiv** [comment]
Care to explain why? They are not going to cause issues as it will be just checks with tests.

Even now some of the checks are distro specific only.

**Comment by Conan-Kudo** [comment]
Mainly because it's going to be hard to keep up with all the extra code from those checks. And some of those checks are *really* irrelevant to us all.

A quick look through indicates the following checks are okay for contributing upstream:
* `BashismsCheck` (disable by default)
* `Check4Xinetd` (disable by default)
* `CheckBuildDate` (enable by default)
* `CheckBuildRoot` (enable by default)
* `CheckDBusPolicy` (needs some refactoring, but enable by default after)
* `CheckExecDocs` (remove `-lang` package related checks, enable by default)
* `CheckFilelist` (needs reworking to match unified base FHS, drop SUSE prefix, enable by default)
* `CheckIconSizes` (enable by default)
* `CheckLogrotate` (needs reworking to drop SUSE prefix, drop mandate for `%dir /var/log` in every package, disable by default)
* `CheckPkgConfig` (needs tweaking, also incorporate #95, enable by default)
* `CheckSysVinitOnSystemd` (needs reworking, drop SUSE prefix, disable by default)
* `CheckSystemdInstall` (needs to be redone to validate on upstream systemd macros, disable by default)
* `DuplicatesCheck` (references to `/srv` need to be replaced with `/var` path variants, enable by default)
* `LibraryPolicyCheck` (needs to be massively reworked and simplified, disable by default)
* `TmpFilesCheck` (disable by default)

**Comment by scarabeusiv** [comment]
Yea I know it will be bit more work, but we already maintain those and will continue to do so. And having them in one repo makes sense for us to avoid divergence.

We will of course streamline them. Frankly we have to as at the moment they won't work with 2.0 at all and with the changes we are doing :)

**Comment by marxin** [comment]
I'm going to work on that.

**Comment by marxin** [comment]
> * `CheckSystemdInstall` (needs to be redone to validate on upstream systemd macros, disable by default)

@Conan-Kudo  Which `systemd` macros do you mean?

**Comment by Conan-Kudo** [comment]
@marxin These: https://github.com/systemd/systemd/blob/master/src/core/macros.systemd.in

**Comment by marxin** [comment]
@scarabeusiv: About the `LibraryPolicyCheck`: we'll have to take a look at https://rpmlint.opensuse.org/rules/openSUSE:Factory/x86_64/standard and select warnings that we want to port. It probably does not make sense to port all of them.

**Comment by dirkmueller** [comment]
@scarabeusiv fwiw I agree that we shouldn't just merge "SUSE specific" checks into this repository unless there is a way to generalize that for other distributions.

**Comment by scarabeusiv** [comment]
Apart from librarypolicycheck that needs ton of work the checks were moved. The remainder is tracked in #371 and we can as such close this ticket.
