### ISSUE TITLE
Recursive dependency size statistics

### ISSUE THREAD

**Issue by leo-lb** [rpm-software-management/rpmlint#264]
Hello,
Along with the Minimization Team at Fedora, we want to provide maintainers a way to evaluate the impact their packages and the dependencies they pull in have on the final system size.

Someone has written this: https://pagure.io/minimization/dependency-visualiser ; which allows someone to generate a graph for any given RPM installed in a custom installroot so it shows size for the main package and all dependencies.

What is the best way you think to integrate this into rpmlint?

The reason I'm asking this is because we concluded it would be best to show this informations to maintainers on Bodhi (e.g. https://bodhi.fedoraproject.org/updates/FEDORA-2019-c8270fe288), and under "Automated Tests" that's where rpmlints are run.

Thank you

**Comment by scarabeusiv** [comment]
I can tell you that we graph this data in OBS and have this information when we create rings in SUSE. Mostly we use it for buildcycles calculations and similar.

Now the question is what exactly should rpmlint do for this because by default it just scans unpacked/installed rpms and does analysis on it, nothing much more.

With this approach you would have to fire up a container (or something along the way) add the rpms passed as an argument (or extract them from installed FS) and try to install them in there, and if everything worked validate the size.

**Comment by Conan-Kudo** [comment]
It probably doesn't make sense within rpmlint itself, but it would be a good idea to develop that into a generic test tool and host it here in this organization for discovery purposes.

Perhaps Fedora Minimization and @asamalik would like to make the visualizer available here?

**Comment by leo-lb** [comment]
@Conan-Kudo I didnt mean dependency web statistics but indeed size statistics.

**Comment by Conan-Kudo** [comment]
You are talking about install root sizes, which is a function of the dependency web.

**Comment by Conan-Kudo** [comment]
I think this check is not appropriate for rpmlint, so I'm closing this for now.
