### ISSUE TITLE
Tmpfiles.d %files rules

### ISSUE THREAD

**Issue by kstreitova** [rpm-software-management/rpmlint#326]
In rpmlint we currently check if the tmpfile created via tmpfiles.d is listed in the %files section and we advise to list it as a %ghost.

However, in [openSUSE tmpfiles.d packaging wiki ](https://en.opensuse.org/openSUSE:Systemd_packaging_guidelines#Creating_files_and_subdirectories_in_.2Fvar.2Frun_and_.2Frun) is no mention about %ghost. The same applies for 
[Fedora](https://fedoraproject.org/wiki/Packaging:Tmpfiles.d#Example_spec_file) but it uses %verify(not size mtime md5) instead (for files).

So my question is what are the correct rules we want to check in rpm lint regarding tmpfiles.d and %files section.

Thanks!

**Comment by Conan-Kudo** [comment]
@jasontibbitts @decathorpe Are the Fedora rules on that wiki page still correct? I see people using `%ghost` more than I do using the odd `%verify` stuff...

**Comment by decathorpe** [comment]
@Conan-Kudo wow, I've never seen `%verify(foo)` anywhere, and didn't even know it existed ... I only know of `%ghost`, and it's what I would use in this case.

By the way, the authoritative source of these packaging guidelines is now [here](https://docs.fedoraproject.org/en-US/packaging-guidelines/Tmpfiles.d/), barring formatting issues that happened when converting them from the wiki page. But looking at the source for the `tmpfiles.d` page, it hasn't been updated or verified yet since the initial conversion from wiki markup to AsciiDoc.

**Comment by Conan-Kudo** [comment]
@kstreitova @decathorpe I'm not sure `%ghost` is necessary for stuff in `/run` anymore, since it's more or less guaranteed to be tmpfs now. `%verify` is definitely overkill.

**Comment by Conan-Kudo** [comment]
@kstreitova @decathorpe is [bringing this up to the Fedora Packaging Committee](https://pagure.io/packaging-committee/issue/927), so we'll have an answer soon.

**Comment by kstreitova** [comment]
@Conan-Kudo Any news regarding creating a tmpfile macro that was mentioned in the Fedora meeting? Thanks!

**Comment by Conan-Kudo** [comment]
@decathorpe has been entrusted to design Fedora's `tmpfiles.d` policy...

@decathorpe, have you figured out how it should work yet?

**Comment by decathorpe** [comment]
@Conan-Kudo I didn't have much time to look into this yet, sorry.

However, reading the max-rpm page about `%files` directives, it sounds like `%ghost` fits the `tmpfiles.d` usecase pretty well (since it only marks the files as "owned" by the package and makes sure it's removed upon package removal, but does nothing else), and `%verify` is more tailored towards situations where file mode / ownership / mtime / checksum cannot be guaranteed to be stable (or determinable at build time).

See: http://ftp.rpm.org/max-rpm/s1-rpm-inside-files-list-directives.html

**Comment by kstreitova** [comment]
I think that it sounds reasonable. So do we want to make rpmlint to check if tmpfile is listed as a %ghost in the %files?

**Comment by hroncok** [comment]
I think we do.
