### ISSUE TITLE
False positive detecting ipxe scripts

### ISSUE THREAD

**Issue by awilliam** [rpm-software-management/rpmlint#350]
iPXE is a pre-boot execution environment for network booting, it supports text file scripts making use of a shebang, ie. #!ipxe.  See https://ipxe.org/scripting  These script files are delivered to the booting system via network protocols such as tftp or http, therefore file permissions and interpreter checks on the boot server are irrelevant.  Attempting to deliver such a script via an RPM results in the following rpmlint errors:

E: wrong-script-interpreter /path/to/delivered/ipxe/script ipxe 
E: non-executable-script /path/to/delivered/ipxe/script 644 ipxe

Is it possible to create an exception for such scripts?  We could work around the second error by delivering the script as an executable, but that seems like the wrong solution.  I don't know how to work around the first error, there is no interpreter for an ipxe script on the host system and there's not intended to be.  Thanks,
Alex

**Comment by scarabeusiv** [comment]
Yup the shebang detection is fairly basic so we just have to exclude this one and add test for it.

**Comment by StykMartin** [comment]
Hi @scarabeusiv,

any update on this one?

**Comment by scarabeusiv** [comment]
Nope, still just tracked, the fix itself is trivial, but the test that should be doing it needs redesign, so it is kinda on the backlog with the other milestone bugs still being open. But feel free to prep it, refactoring with existing code is still easier than writting stuff from scratch (esp. if the code has a testcase).

**Comment by StykMartin** [comment]
@renanrodrigo can you take a look and figure out a patch for this issue?

**Comment by renanrodrigo** [comment]
As far as I can see, this is already fixed in upstream and released for 1.11.

The first error was removed in a4618650898aece5c4838e71853310b54f6e29fa - it only considers `ipxe` as a "wrong interpreter" if the file is executable (and it should not be) or if it matches the script_regex - also avoidable imho.

The second error is removed in 5d7e50accf8100247e52509a8b00fb831f54278d just by verifying that the interpreter name starts with a `/` - which is not the case.

**Comment by scarabeusiv** [comment]
Based on the last comment we can consider this fixed.
