### ISSUE TITLE
warn on packages having build or runtime dependencies on deprecated packages

### ISSUE THREAD

**Issue by mcepl** [rpm-software-management/rpmlint#451]
We are now in the process of eliminating nose from Factory, we shouldn’t let another package requiring it slip back (e.g., see https://build.opensuse.org/request/show/825902).

**Comment by Conan-Kudo** [comment]
Hmm, this should probably be genericized to actually add a policy to warn on requiring packages that have `Provides: deprecated()`.

Cf. https://docs.fedoraproject.org/en-US/packaging-guidelines/deprecating-packages/

**Comment by mcepl** [comment]
@scarabeusiv  Just sneakily adding you into CC. What do you think?

**Comment by Conan-Kudo** [comment]
Also... @hroncok, @decathorpe, you may want to weigh in here?

**Comment by decathorpe** [comment]
insert "THIS IS FINE" GIF here

fwiw, fedora-review actually checks this for new packages, it's just that some people tend to ignore fedora-review output. having it in rpmlint would be nice.

**Comment by hroncok** [comment]
does rpmlint run repoqueries? if it doesn't then I don't know how to accomplish this.

**Comment by scarabeusiv** [comment]
I agree with Miro, there is no actual way how to check this up at the moment as we check just whats within the pkgs, we don't check the requires, nor do we check the if the pkg can be installed.

The only item I can see here is if we would run it on the installed rpm within existing system. (which is possible but almost nobody runs the rpmlint in this way).

If you figure some way how to have this information presented in offline form to rpmlint then it could be done, otherwise I think this is CANTFIX.
